# Generated by Django 3.2.14 on 2022-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('PostedDate', models.DateTimeField(auto_now_add=True)),
                ('JobTitle', models.CharField(max_length=255)),
                ('CompanyName', models.CharField(max_length=255)),
                ('Salary', models.CharField(max_length=255)),
                ('Skills', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
