# Generated by Django 3.2.14 on 2022-11-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='WorkTime',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
