# Generated by Django 3.2.14 on 2022-11-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HrEntry', '0002_joblist_worktime'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('AppliedDate', models.DateTimeField(auto_now_add=True)),
                ('JobTitle', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('EmailId', models.CharField(max_length=255)),
                ('Document', models.FileField(upload_to='resumes')),
                ('Jobid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HrEntry.joblist')),
            ],
        ),
    ]
