# Generated by Django 3.2.14 on 2022-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrEntry', '0004_auto_20221110_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropedResume',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('AppliedDate', models.DateTimeField(auto_now_add=True)),
                ('JobTitle', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('EmailId', models.CharField(max_length=255)),
                ('Document', models.FileField(upload_to='droped_resumes')),
            ],
        ),
    ]
